### ISSUE TITLE
mettre à jour le serveur?

### ISSUE THREAD

**Issue by PatGendre** [fabmob/e-mission-phone-fabmob#12]
vérifier si on a bien mis à jour les derniers commits sur notre fabmob
même si ce sont des modifs mineures c'est mieux de le faire
https://github.com/e-mission/e-mission-server/commits/master

**Comment by DO3B** [comment]
C'est fait normalement https://github.com/fabmob/e-mission-server-fabmob/commit/bb8e82c5fc70b5f87fc4e8a038313d48230ca1f1
