### ISSUE TITLE
update the app web site

### ISSUE THREAD

**Issue by PatGendre** [fabmob/e-mission-phone-fabmob#13]
In the process of the restructuring the docs, it appears that the e-mission doc for the app end-user better be separated from the [rest of the doc](https://github.com/fabmob/e-mission-docs/) in a web site. And there is a web site along with the app web server.   
For e-mission, this site is https://e-mission.eecs.berkeley.edu/.    
For traceur fabmob, this site is https://fabmob.grfmap.com:8080/
So we should [adapt the server site](https://github.com/e-mission/e-mission-server/tree/master/webapp/www) to the traceur app. In French first, possibly also in English : 
- change the title and screenshots  
- adapt the content  
- explain how to use the app, [based on existing Google doc](https://docs.google.com/document/d/1X_FwiXjmWEFCLNhEXNa3-cD0FCjOURlLClCUiUoQ6PM/)  

Low priority ; to be done after i18n, surveys, and profile screen (and after grfmap).

**Comment by PatGendre** [comment]
@DO3B I updated the master branch with some info specific to fabmob (FAQ in French, homepage), but I have the impression that ReadTheDocs doesn't show the updates because e-misions-docs for fabmob doesn't principal branch is e-mission-contrib which is fork which pulls from e-mission, and e-mission-docs master is not pulling from e-mission.  
Can you confirme my impression : how can we generate the readtheme HTML files from the master branch of e-mission-docs/master?

**Comment by DO3B** [comment]
On our doc, we are generating from the https://github.com/fabmob/e-mission-docs/tree/master branch (https://fabmob.readthedocs.io/en/latest/, we can see your FAQ).

**Comment by PatGendre** [comment]
Ok, thanks! I think I didn't see the changes because the pages were cached on my browser, I refreshed it.

Where did you configure readme to use the Sphinx theme instead of the mkdocs theme? This is better, we only need to change colors if possible now ;-)

**Comment by DO3B** [comment]
I just added `theme: readthedocs` to `mkdocs.yml`

**Comment by PatGendre** [comment]
Ok, I looked in the firs tlines of the mkdocs.yml and it was at the end of the file, no problem :-)

**Comment by PatGendre** [comment]
minimal web site design : screenshots, links to frama site, readthedocs, Gdoc user manual, app store, contact fabmob e-mail in FR+EN. and arrow keys that work ;-)

**Comment by DO3B** [comment]
I changed a bit the design of the Website and disabled for now the heatmap (https://github.com/fabmob/e-mission-server-fabmob/commit/8eea4a0b43d5aef689523eca6fc178d9799d7e93). I will renabled it when I make it works. I also need to take more screenshots. Obviously, it is also available in english.

|Main|Intro|
|---|---|
|![Capture d’écran 2019-07-25 à 13 34 31](https://user-images.githubusercontent.com/17317703/61871553-68c31200-aee1-11e9-9d64-f3474e89960f.png)|![Capture d’écran 2019-07-25 à 13 34 38](https://user-images.githubusercontent.com/17317703/61871539-6365c780-aee1-11e9-8811-cf7417e90683.png)|

|Personal|Code|
|---|---|
|![Capture d’écran 2019-07-25 à 13 34 43](https://user-images.githubusercontent.com/17317703/61871506-4f21ca80-aee1-11e9-8c71-b86771a73b67.png)|![Capture d’écran 2019-07-25 à 13 34 47](https://user-images.githubusercontent.com/17317703/61871485-43ce9f00-aee1-11e9-977e-81775d1aab04.png)|
