### ISSUE TITLE
improve e-mission-docs

### ISSUE THREAD

**Issue by PatGendre** [fabmob/e-mission-phone-fabmob#15]
fabmob e-mission-docs 
e-mission-contrib branch + fabmob.readthedocs.io
- repair links : relative paths for images (assets) and internal pages 
master branch
- css : fabmob colors green for upper left box and yellow for chapters

**Comment by DO3B** [comment]
Normally, I fixed all the broken links (https://github.com/fabmob/e-mission-docs/commit/0a9da712377f1f07081c6f5d042ccba35cbc8810). I will now try to change a bit the css. I had to move `assets/` into `docs/ `because I found in the **mkdocs**'s doc that it should be there.

**Comment by DO3B** [comment]
I changed the theme for `mkdocs-material` (https://github.com/fabmob/e-mission-docs/commit/9408345849d808825f53ef06e463b37c264a8b20) and added the fabmob logo where I can. The build passed so you can check the new theme: https://fabmob.readthedocs.io/en/latest/

**Comment by PatGendre** [comment]
excellent, congratulations :-)) 
Almost perfect, except I don't find the readthedocs widget for choosing version and switching to the readthedocs site?

**Comment by DO3B** [comment]
It seems that it is a feature not yet implemented in custom themes.

**Comment by PatGendre** [comment]
Ok, not a big problem. If we could have a simple link to https://readthedocs.org/projects/fabmob/ somewhere in the top bar it could be enough. Is this easy to do?

**Comment by DO3B** [comment]
It should be easy to do but it might be more interesting to add it to the sidebar like you added the GitHub issues. 
![Capture d’écran 2019-07-16 à 10 19 03](https://user-images.githubusercontent.com/17317703/61277813-36b00280-a7b3-11e9-98a4-66450baeb776.png)

**Comment by DO3B** [comment]
By looking at the console log, I noticed that ReadTheDocs widget needed jQuery. I added it (https://github.com/fabmob/e-mission-docs/commit/0d88403dbf5f5e9ec13706413724a2acea456fc5) and it works.

**Comment by PatGendre** [comment]
Great! So I don't have to update the yml :-)
The widget font is very small, can you make it larger please?

**Comment by DO3B** [comment]
I checked a bit and the widget is injected after the compilation. It seems to be linked to the fact that the font-size of our theme is 0.5rem which is relatively small. I will for now change the font-size of the `injected` class in order to make it bigger (https://github.com/fabmob/e-mission-docs/commit/06f16df38249f410d228c9ad18a8f888641d52b7).

**Comment by PatGendre** [comment]
Ok, fine, thanks a lot !

**Comment by DO3B** [comment]
While trying to find some information on the pipeline, I found some MarkDown syntax errors so I corrected them (https://github.com/fabmob/e-mission-docs/commit/d9743bd7b774884c0e13be9fbcc320b45d8b712e) and added the WebHook of ReadTheDocs to build automatically at each push. Can I remove the GitBook's WebHook ?

**Comment by PatGendre** [comment]
Ok thanks, yes you can remove the hook.
