### ISSUE TITLE
phone app internationalisation

### ISSUE THREAD

**Issue by PatGendre** [fabmob/e-mission-phone-fabmob#2]
see issue https://github.com/e-mission/e-mission-docs/issues/354
0. check translatewiki requirements
1. update plugins 
2. update app (html/js)
3. update conf file (mode / purpose)

**Comment by DO3B** [comment]
1. For more details: https://github.com/e-mission/e-mission-docs/issues/354#issuecomment-499889286 
2. Currently working on it : https://github.com/fabmob/e-mission-phone-fabmob/tree/i18n

**Comment by DO3B** [comment]
3. This commit allows us to translate the custom modes and purposes https://github.com/fabmob/e-mission-phone-fabmob/commit/91d8d8bdba03c92de8c3667769663350f56a1a9c

**Comment by DO3B** [comment]
https://github.com/e-mission/e-mission-phone/commit/f03c1fff43933141c33eb1723e501f871ffaad94

**Comment by PatGendre** [comment]
Ok i18n is solved but we have to complete it so that the app update is deployed : 
1) translate the plugin (patrick)
2) write a hook for the phone-app for internationalisation
3) publish the updated app, inform the users
4) inform Shankari, see if she validates our approach for the hook, update the docs
5) hopefully, test translatewiki
6) inform the Germans and Italians

**Comment by PatGendre** [comment]
Our approach is that all translations are managing at the app level (by a cordova hook), not at the plugin level, because the plugins anyway are only used by e-mission, the plugins are not published on the cordova directory for the moment so that they be reused by others.

**Comment by DO3B** [comment]
https://github.com/fabmob/e-mission-phone-fabmob/commit/02449bbedb30a21fa42c454531d5a6301c21fff0 
I moved our translations in the `locales` folder with the architecture I suggested to Shankari,(https://github.com/e-mission/e-mission-docs/issues/354#issuecomment-505003951) and  added the hooks for both iOS and Android. It might be interesting to add a third hook for the `www` folder  since it is used by the two platforms.

**Comment by PatGendre** [comment]
Ok so you're almost done?
Still need to add PR to https://github.com/e-mission/e-mission-translate so as to create the locales fr directory there? + send me the plugin key-value file so that I translate it.

**Comment by PatGendre** [comment]
I close the issue, even if we still wait for translatewiki answer, this is done for the code
