### ISSUE TITLE
alert the admins in case of pipeline errors

### ISSUE THREAD

**Issue by PatGendre** [fabmob/e-mission-phone-fabmob#20]
the logs are quite verbose, we need to identify problems that need admin intervention and describe them simple rules so that they can be detected automatically and notified to the admin.

One on the errors is when a pipeline stage n is not executed; in the /var/emission/em-script/show_pipeline.py script, this is detected when the last_ts_run of stage n is before last_ts_run of stage n+1.
In that case, either log the error in a special directory alerts in a daily file and/or e-mail it to the admins.

**Comment by DO3B** [comment]
I looked a bit at [notify.run](https://github.com/paulgb/notify.run). It is really easy to configure and run. As we are just sending a notification without any confidential data (just a "Error(s) in the pipeline, you should check intake_global-errors.log"), I suggest that we use for now there endpoint. I created this channel for now: https://notify.run/c/gp4ekyBL51VAoNdi (I will add it to the doc).

**Comment by PatGendre** [comment]
ok, it seems a good solution, simpler than e-mail

**Comment by DO3B** [comment]
I added a page into the doc explaining the current state of the logs and how to configure and use notify.run https://fabmob.readthedocs.io/en/latest/manage/managing_the_logs/

**Comment by PatGendre** [comment]
Ok, fine :) Next time you talk to Fouad, this will be useful for grfmap import logs as well. (and maybe in the future for monitoring mongodb logs?).

If I understand well, for the moment the notification will be done in case of error in the intake logs, not in the webserver log.
Also, there is nothing to configure on the phone for enabling notifications?

**Comment by DO3B** [comment]
You just need to open the link on your mobile phone's browser(by either scanning the QR code or just clicking on it) and click on "Subscribe on this device". The browser may open a prompt asking you if you accept to receive notifications from it. For now, it concerns only the intake logs.

**Comment by PatGendre** [comment]
Ok, it works. Good

The URL is public in the doc, so anybody could see when we get errors, but that's not an issue for the moment ;-)

**Comment by DO3B** [comment]
We can easily switch the channel later or create our self-host instance. We will see tomorrow if we are receiving a notification around 7 AM.

**Comment by DO3B** [comment]
After few days of running, the script works. When we check the notify.run channel, we can see that everyday, we have an error. It might be necessary to switch the channel later as it is public right now and in the doc.
