### ISSUE TITLE
add tram and metro modes

### ISSUE THREAD

**Issue by PatGendre** [fabmob/e-mission-phone-fabmob#21]
the metro and tram modes are currently not distinguished from TRAIN in the [GIS_based_mode_detection branch](https://github.com/e-mission/e-mission-server/blob/gis-based-mode-detection/emission/analysis/classification/inference/mode/rule_engine.py) (ex. ground_truth_matching branch).
This feature is wished y many users. See [issue 428 in e-mission](https://github.com/e-mission/e-mission-docs/issues/428).

The enhancement would consist of:
- in the server, finding what are the OSM tags used for tramway and metro, to distinguish them from TRAIN in the mode
- in the phone app, updating the dashboard and diary views with the modes : add a new color and icon, complete the indicators (CO2, trips/km/duration/speed) with the 2 modes.

An alternative would be to redesign the UI as there would now quite a lot of modes, and more could be added especially if we added the modes and purposes info filled in by the user, but this alternative seems currently not feasible in the short term (August), as we would need end-users for that, and possibly an designer.

**Comment by DO3B** [comment]
It seems a bit more complex that anticipated. First of all, we have to change [collapse_modes(section_entry, modes)](https://github.com/e-mission/e-mission-server/blob/gis-based-mode-detection/emission/analysis/classification/inference/mode/rule_engine.py) but if there is more than two modes, we have to change Shankari's way to arbitrary decide between train and bus (based on the speed...). Moreover, there is another issue, if there is no routes ([get_predicted_transit_mode(start_stops, end_stops)](https://github.com/shankari/e-mission-server/blob/dc60ccdfab34e0be4fe76154911243e648085672/emission/net/ext_service/transit_matching/match_stops.py)) how can we now if the user took the tram, subway or train by just looking at the start and the end of the section ? Most of the train station are also subway and bus station. We also need to add the two new modes [there](https://github.com/e-mission/e-mission-server/blob/gis-based-mode-detection/emission/core/wrapper/modeprediction.py).

**Comment by PatGendre** [comment]
yes, you are right, the detection mode stage of the pipeline (GIS branch) needs to be investigated, understood and updated before we envisage to update the UI. Thanks in advance for opening an issue for asking Shankari on how to proceed. I put a STUDY tag for the moment on this issue. You don't need to solve the problem for all cases, but you'll have to find the simplest solution that works for at least a good half of the cases so that adding tram and metro brings a real improvement, rather than bringing new complications!

I've just has a main from Massimo in Italy saying that for its return trip from Roma to Milano, it was detected once as Plane/Hi Speed Train, and once as car, so this needs to be improved, too...
See also [issue 363](https://github.com/e-mission/e-mission-docs/issues/363) and [issue 241](https://github.com/e-mission/e-mission-docs/issues/241)

**Comment by DO3B** [comment]
As Shankari suggested, I added logging if we reach the speed check (https://github.com/fabmob/e-mission-server-fabmob/commit/4b2b7694174f9b127474d5c8eba6f8172e618f12) and if there is no route `get_predicted_transit_mode` will now also checks the tags of the nodes containing "railway" (https://github.com/fabmob/e-mission-server-fabmob/commit/b8ebb8d01ac087d0822ec121727dad09673e19d5). I will now work on the UI.

**Comment by DO3B** [comment]
I added the two new modes to the phone app (https://github.com/fabmob/e-mission-phone-fabmob/commit/8c9ec6878f9251c2f1eb775a44069c7fc897e297). I just have to found the carbon footprint ratio of the two modes. I also added [FontAwesome](https://fontawesome.com/) to have two new icons for both tram and subway.

**Comment by DO3B** [comment]
Thanks to Susanne data, I was able to fix an issue on the server (https://github.com/fabmob/e-mission-server-fabmob/commit/c99bfbcebb54ca66f0866d7329065001ffe18e81) and test it on the phone app. 

The icons for the [subway](https://fontawesome.com/icons/subway?style=solid) (one more headlight than the train) and [tram](https://fontawesome.com/icons/tram?style=solid) are:

|Subway|Tram|
|---|---|
|![image](https://user-images.githubusercontent.com/17317703/61794339-4669bf80-ae21-11e9-86d4-118786bf4773.png)|![image](https://user-images.githubusercontent.com/17317703/61794423-75803100-ae21-11e9-850e-a0d46b9d0666.png)|

And as you can see below, the subway is now detected.

|Diary|Metrics|
|---|---|
|![Screenshot_1563970807](https://user-images.githubusercontent.com/17317703/61794061-b3c92080-ae20-11e9-9eb1-6461b826d65b.png)|![Screenshot_1563970826](https://user-images.githubusercontent.com/17317703/61794100-c5aac380-ae20-11e9-92ab-32efd719141a.png)|

**Comment by DO3B** [comment]
@PatGendre I updated the server with the latest commits of Shankari in both the master and gis branches. We can now disable some asserts through a `debug.conf.json` file ([debug.conf.json.sample](https://github.com/fabmob/e-mission-server-fabmob/blob/master/conf/analysis/debug.conf.json.sample)). We are currently using the following `debug.config.json`: 
```
{
    "intake.segmentation.section_segmentation.sectionValidityAssertions": true,
    "intake.cleaning.clean_and_resample.speedDistanceAssertions": false,
    "intake.cleaning.clean_and_resample.sectionValidityAssertions": false,
    "intake.cleaning.filter_accuracy.enable": false,
    "classification.inference.mode.useAdvancedFeatureIndices": true,
    "classification.inference.mode.useBusTrainFeatureIndices": true,
    "classification.validityAssertions": true,
    "output.conversion.validityAssertions": false,
    "section.startStopRadius": 150,
    "section.endStopRadius": 150,
    "analysis.result.section.key": "analysis/inferred_section"
}
```
  Moreover, we can also change the radius of start and the end stops. This should helps us with the overpass queries because if we reduce the radius, we will query smaller zones.

**Comment by PatGendre** [comment]
@DO3B ok great! There are many config params, for the radius in dense cities, we may try 100m or even 50, if we have too many overpass API calls.

**Comment by DO3B** [comment]
Shankari merged this and I updated the branch master (https://github.com/fabmob/e-mission-phone-fabmob/commit/ffdbde5345ba312697b12745b670b262e0cb01de). We have now 3 new modes, this closes the issue :)
