### ISSUE TITLE
improve location display with adresse.data.gouv

### ISSUE THREAD

**Issue by PatGendre** [fabmob/e-mission-phone-fabmob#27]
This is small and unimportant enhancement in the Profile screen : displaying the location using the national adress database when the user position in France, instead of nominatim.
See the doc : https://adresse.data.gouv.fr/api

**Comment by PatGendre** [comment]
@DO3B great to have closed this! Does it imprive the geolocation wrt OSM, did you test a little?

**Comment by DO3B** [comment]
I tried it with different location since I had to test the limit of the API to use Nominatim if the API returns nothing or if the user is not in France. The return values (addresses) seems pretty accurate (but I also used accurate lat and long).

**Comment by PatGendre** [comment]
ok, good, thanks!

**Comment by PatGendre** [comment]
ok, good, thanks!
