### ISSUE TITLE
complete the Profile screen

### ISSUE THREAD

**Issue by PatGendre** [fabmob/e-mission-phone-fabmob#28]
- when available ([see issue 433](https://github.com/e-mission/e-mission-docs/issues/433)), we can display the geofence location 
- also, we could display the wifi geolocation parameter of the phone instead of wifi network parameter, if available (to be confirmed), and possibly similar geoloc parameter for cell network and bluetooth if available

**Comment by DO3B** [comment]
I looked the doc of [cordova.plugins.diagnostic](https://www.npmjs.com/package/cordova.plugins.diagnostic#isnetworklocationavailable) and we may be able to retrieve those information (for cell network and Wi-Fi) on Android but there is no equivalent function for iOS and for bluetooth.

> isNetworkLocationEnabled()
> Platforms: Android
>
> Checks if location mode is set to return low-accuracy locations from network triangulation/WiFi > access points Returns true if Location mode is enabled and is set to either:
>
> Battery saving = network triangulation and Wifi network IDs (low accuracy)
>
> High accuracy = GPS hardware, network triangulation and Wifi network IDs (high and low accuracy)
>
> cordova.plugins.diagnostic.isNetworkLocationEnabled(successCallback, errorCallback);

**Comment by PatGendre** [comment]
Ok, thanks so for the moment don't go for implementation.
What you could do is add a directory "enhance Traceur Fabmob" just after Future in https://fabmob.readthedocs.io/ with a first page on this topic (monitoring user geolocation status), where you would copy-paste what you've found. I can complete if you wish.

**Comment by PatGendre** [comment]
As discussed today with Massimo, tester in Italy, we can **remove the medium accuracy** button in the next version, because the tracking is really worse, it detects the stops but the route/itinerary is not precise and thus not very useful. This button can be useful for tracking evaluation but is rather "dangerous" for end-users as they might switch to medium accuracy without knowing what it does and then lose a few trips (or worsen the tracking quality).

**Comment by DO3B** [comment]
I removed the Medium Accuracy button as you asked (https://github.com/fabmob/e-mission-phone-fabmob/commit/f3bd2aea94b146d01a59e77978868c0c8cd375d0).

**Comment by PatGendre** [comment]
Thanks!

**Comment by DO3B** [comment]
I added to the doc what you asked ([Complete Profile screen](https://fabmob.readthedocs.io/en/latest/dev/future/enhance_traceur_fabmob/profile_screen/)). I may have found why we can't retrieve the accuracy on iOS, I wrote the reason in the doc.

**Comment by PatGendre** [comment]
Thanks! It is good to keep track of this if someone wants to work on it later on.
Could you move the Enhance traceur one level up (same level as "Future")?
