### ISSUE TITLE
mongodb backup

### ISSUE THREAD

**Issue by PatGendre** [fabmob/e-mission-phone-fabmob#29]
As far as I know, we don't backup the mongodb base. We should do something about it.

We could also archive the user's timeline regularly, [there are scripts](https://github.com/e-mission/e-mission-server/tree/master/bin/debug) for that. So if a user loses his/her data (or WE lose the data), we could restore it or at least make it available to him/her (GDPR).

**Comment by DO3B** [comment]
Following the issue of this morning, I created a backup script (`mongo_backup_weekly.py`) into `em-scripts` which will backup the DB every monday morning at 6AM. The backup files will compressed in `/var/emission/backup/` and will have the following name "`Stage_database-date.gzip`".

**Comment by PatGendre** [comment]
Thank you Loïc @DO3B

**Comment by DO3B** [comment]
I added a page to the doc https://fabmob.readthedocs.io/en/latest/manage/backup_restore_mongodb/
