### ISSUE TITLE
test surveys

### ISSUE THREAD

**Issue by PatGendre** [fabmob/e-mission-phone-fabmob#3]
to be defined

**Comment by PatGendre** [comment]
see this file in French
https://docs.google.com/document/d/1-FpWQXYW4CI_hErbwP_Zk9wc8hvup8Un5r7rHwLjOcQ/

**Comment by PatGendre** [comment]
Update June 24 : 
- use limesurvey (open source, free plan, python API)
- the firebase notification works correctly even if the app is in background (force mode)
- test limesurvey python API -> https://manual.limesurvey.org/RemoteControl_2_API#Python_example_and_glue
1) add users to a manually created survey ; we will have to use e.g the last 10 digits (or another hash) of the UUID as limesurvey UserID (otherwise the uuid string would be too long)
1bis) add participants from the e-mission-server script (add option -limesurvey in CLI) so that the participants notified by-emission are automatically added in limesurvey
2) ask limesurvey for the list of surveys for a participant, with URL link to the survey for that user (with token, survey status - e.g. on going or finshed -, response status - responded or not -)
2bis) embed the surveys list response to the previous request in an HTML Survey displayed in the phone app
3) try out the whole chain on the android apk
4) check ow to make the notification work also for APNS (currently it doesn't work, maybe due to a problem in our conf? firebase does not properly notify APNS)

**Comment by DO3B** [comment]
1. https://github.com/fabmob/e-mission-server-fabmob/commit/3750c952b0589d1f803c585c8da1aac008cad3a0 I manage to change the length of a LimeSurvey token (32 characters now) to be able to use the UUID of a user, by doing this we will not be forced to adapt the existing database.
I also modified `send_survey.py` to answer our needs. We can add LimeSurvey participants either by mail or uuid. 
2. I will now try to create a REST api for that.

**Comment by PatGendre** [comment]
1. good news :-))
2. Ok, tell me and if you have questions and I can help.
I hope the python request to LimeSurvey will work smoothly.
If I understand well, the REST API will be then used by the app to display the surveys for the app user?

**Comment by DO3B** [comment]
1. https://github.com/fabmob/e-mission-server-fabmob/commit/55ae5572784cf4f972e26cc0a1b7baeb9b5992b2 I made some changes to avoid spamming the user if I already completed the survey.
2. The POST request `/survey/get` works, I will now try to create a UI.

**Comment by PatGendre** [comment]
Ok, it is progressing well, I can try the api next monday to see how it works

**Comment by DO3B** [comment]
3. https://github.com/fabmob/e-mission-phone-fabmob/commit/695d593ddd0aa2d14e3eeb887b9ae76f9d058b98 

Without ongoing surveys | With ongoing surveys
--- | ---
 ![Screenshot_1561726008](https://user-images.githubusercontent.com/17317703/60343217-56000080-9968-11e9-8f24-bbf9b4c3c757.png) | ![Screenshot_1561725575](https://user-images.githubusercontent.com/17317703/60342958-b6db0900-9967-11e9-9f0d-6d67ec6ee6ca.png) 

I started to work on the Surveys screen, you can access to the survey by clicking on it. If you have already completed it, you can check or change your responses by also clicking on it.

**Comment by PatGendre** [comment]
Great !
If I remember well this will be internationalised (the survey phone UI)? Is it possible also with limesurvey to have several language of the same survey?

Another question about limesurvey : is it possible to configure a survey so that the user cannot modify the answer once he has completed and validated the form?

Last question : on the screen, do we display also the surveys which are finished? (i.e. whether the user has answered or not, it is too late to answer anyway) or do we display only the active surveys? (I suppose the latter is true)

**Comment by DO3B** [comment]
When we create a survey, it is possible to configure multiple languages. It may be necessary to stock somewhere the different titles because I am currently displaying the "main" title. 

It is possible to configure a survey so that the user cannot modify the answer once he has completed it but it seems that this will prevent the user from accessing his response. 

We are only displaying the active surveys.

**Comment by PatGendre** [comment]
Ok thanks, so in the screen the main title should "Ongoing surveys" (synonym of active, for me ; enquêtes en cours), and the title below should be "Unanswered Surveys" (or Surveys to complete / not completed; enquêtes non renseignées).

For the moment we will may be test a survey in FR and EN, but we can have a common title for both language for the test as we shall limit the devs to a minimum.

If possible, it would be nice to add the expiration date of each survey ("to complete before...").

**Comment by DO3B** [comment]
I had some issues with iOS and the old UI. So I made some changes to not have to do some heavy changes on the CSS. As you asked, I changed the main title and added expiration date (https://github.com/fabmob/e-mission-phone-fabmob/commit/c56b40aca021de5e0fcf0744f292ee4d67b2abb8). 

| Android| iOS|
|---|---|
| ![Screenshot_1561972786](https://user-images.githubusercontent.com/17317703/60425249-f9d6ef80-9ba6-11e9-9ec2-559593a5f8c8.png)|![Simulator Screen Shot - iPhone Xʀ - 2019-07-01 at 02 22 05](https://user-images.githubusercontent.com/17317703/60425275-078c7500-9ba7-11e9-9538-b82c613e7808.png) |

**Comment by PatGendre** [comment]
@DO3B Ok, fine, thanks. 
It seems quite close to completion. What does still to be done before updating the app?
- complete the doc?
- test the UI, write tests ?
- translate?
I suppose we can publish the update on fabmob before we know if Shankari would be interested for merging the code of parts of if it mainstream e-mission?

**Comment by DO3B** [comment]
- The doc needs to be written (limesurvey configuration and server-side configuration),
- I tested the UI but I may have forgotten some use cases,
- I already translated it.

**Comment by PatGendre** [comment]
Ok, thanks, we can test together the UI this afternoon and possibly write the doc. And then inform Shankari.

**Comment by DO3B** [comment]
I merged the master with the Limesurvey branch (https://github.com/fabmob/e-mission-phone-fabmob/commit/917a008ff6771e5db710adae17b6a67d93c1f337). I think we can deploy an update tomorrow with the Survey screen.

**Comment by PatGendre** [comment]
great!
the update will also include the CO2 screen and the phone app recent corrections?

**Comment by DO3B** [comment]
Yes, I corrected the bug before reporting it to Shankari and the CO2 screen seems to work now.

**Comment by PatGendre** [comment]
Super

**Comment by DO3B** [comment]
https://github.com/fabmob/e-mission-phone-fabmob/commit/917a008ff6771e5db710adae17b6a67d93c1f337
