### ISSUE TITLE
phone UI update in Dashboard

### ISSUE THREAD

**Issue by PatGendre** [fabmob/e-mission-phone-fabmob#7]
There are current small bugs that it is better to hide until they are corrected.

1) remove the CO2 box ([to be corrected soon by TMS Martins](https://github.com/e-mission/e-mission-phone/pull/576/files/68d66af85628fa97092492b93f9b07a81da76dd0..3cc0597b473c5c1b3cf823e4545b8dbacb406787)

2) Calories : 
- if possible add before the number "this week" (dépends on the frequency chosen via the date button)
- when clicking on the unfold arrow, delete Average and comparison with preceding week

3) bottom box  : add a page symbol so that the user understand he/she can swipe the page to see the other screens Distance / Trips / Time / Speed

**Comment by DO3B** [comment]
https://github.com/fabmob/e-mission-phone-fabmob/commit/ed0b7d07e0fccc4ed3fe4ed85fd201e73edc5ede

1. Removed until PR,
2. Average and Last Week removed until fix, 
3. Add pager at the bottom of the card to highlight the different "slides".

![Screenshot_1561458154](https://user-images.githubusercontent.com/17317703/60091021-817cb400-96f8-11e9-8a7a-111bd19de9c4.png)

**Comment by PatGendre** [comment]
Ok, good!
If possible also delete the Calibrate button in Calories, it is useless until the small bug with gender/age/height/weight data is corrected

**Comment by DO3B** [comment]
I removed the `Calibrate` button. https://github.com/fabmob/e-mission-phone-fabmob/commit/55ac125c2e504ab7ab644d65f46ca66b41962a81

**Comment by PatGendre** [comment]
the CO2 emission has been completed by Tiago Martins and pushed to master, we can now *update the app*.

However, in the UI it is not still not clear that the dates are reset to the last 7 days each time we come back to the Dashboard, so even if we cannot store the dates so that they stay the same when we change screen and come back, we should at least  *display the dates* (and possibly also frequency) currently used for the computations.

**Comment by DO3B** [comment]
When updating I found a little bug, I reported it to Shankari.

**Comment by PatGendre** [comment]
Ok thanks

**Comment by PatGendre** [comment]
As said before, the dashboard UI could be clearer :  
- the current dates used for computations should be displayed (and ideally stored when the user comes back); the OK / Get button for the datepicker has to be clicked but this is not clear that it should : so we could rename it compute/calculer or find another widget? (and displaying the current dates will be useful in that respect)

- the graphiques/charts button is only used for the bottom indicators (distance, trip number etc.), this not clear neither
- the frequency is used only used for the bottom indicators, it should be in a separate button or a least the period for computing the totals/average should be displayed in the bottom box
- the units should be changed : hours instead of seconds, km/H instead of m/s

**Comment by DO3B** [comment]
I started to work on those changes. I currently changed the unit for km/h (m/s * 3.6) and "humanize" values for the seconds (https://github.com/fabmob/e-mission-phone-fabmob/commit/06b18b7b46e7568148274fa844224b800bf47be3). 

|Median speed|Duration|
|---|---|
|![Screenshot_1562246728](https://user-images.githubusercontent.com/17317703/60670303-a3043b00-9e70-11e9-8665-19aa35023ba9.png)|![Screenshot_1562246724](https://user-images.githubusercontent.com/17317703/60670314-a697c200-9e70-11e9-94f7-ef6de37f5151.png)|

**Comment by PatGendre** [comment]
excellent! You will also do it on the graphs?

**Comment by DO3B** [comment]
I managed to change the metrics of the graphs. (https://github.com/fabmob/e-mission-phone-fabmob/commit/90d59c23434918a1c522982603288543667df14e, https://github.com/fabmob/e-mission-phone-fabmob/commit/89bd4b2272dd789c37d336f5e6974c5f09ea4362)

|Distance|Duration|Speed|
|---|---|---|
|![Screenshot_1562250588](https://user-images.githubusercontent.com/17317703/60674161-cbdcfe00-9e79-11e9-9aa0-7888e09860c6.png)|![Screenshot_1562250850](https://user-images.githubusercontent.com/17317703/60674168-d13a4880-9e79-11e9-873e-6e114a8517c9.png)|![Screenshot_1562250600](https://user-images.githubusercontent.com/17317703/60674139-ba93f180-9e79-11e9-8548-c06cd3ff97d0.png)|

**Comment by PatGendre** [comment]
Super:-) So I suppose you can complete the other points quickly, at least displaying the current date next to change date button and the frequency next to the indicator box at the bottom, the rest is not urgent.
You can then pass on other issues, like [issue 9](https://github.com/fabmob/e-mission-phone-fabmob/issues/9)

**Comment by DO3B** [comment]
With the last commit (https://github.com/fabmob/e-mission-phone-fabmob/commit/6732fcbeab13f7ad724a963ff5469a22c85fdf6e), we are now able to see the current date.

|Summary|Charts|
|---|---|
|![Screenshot_1562320535](https://user-images.githubusercontent.com/17317703/60715356-1b283a80-9f1d-11e9-8a77-bfe78a76a62d.png)|![Screenshot_1562320537](https://user-images.githubusercontent.com/17317703/60715369-22e7df00-9f1d-11e9-8fd3-f8d93f153c38.png)|

**Comment by PatGendre** [comment]
excellent:-) maybe add an 's' to "changer dateS";

I checked for the frequency / period, it was wrong it has no effect on the indicators, it seems to be useful only for the charts. So it could be displayed only for the graphs (and maybe we could changed the text "frequency" with "chart period" / "période du graphe"

**Comment by DO3B** [comment]
I added the frequencies (https://github.com/fabmob/e-mission-phone-fabmob/commit/59d26b11b077782fd1afa779fb5d5dbc17cb3a78) and fixed some bugs (https://github.com/fabmob/e-mission-phone-fabmob/commit/029c02a45fb0b9ba63d40ca3290b3a38b696b61e).

|Charts|
|---|
|![Screenshot_1562329314](https://user-images.githubusercontent.com/17317703/60722173-66981400-9f30-11e9-84f2-9f3dda9af79c.png)|
