### ISSUE TITLE
phone UI update UI  : Profile Screen

### ISSUE THREAD

**Issue by PatGendre** [fabmob/e-mission-phone-fabmob#8]
** split the Profile in 2 screens 
1) a Status screen (which will be displayed by default instead of the Dashboard)
2) a Parameter screen

** Status: (état in FR)
icon : the same as profile
- user login
- Tracking button
- add "current status" (ongoing trip, waiting...)
- depending on the status : start trip (force from waiting to ongoing) / en trip (for back to waiting) 
(and maybe force sync too, to be confirmed)
- if possible add Wifi status , Data network status, localisation status (not the tracking button, but the GPS/GNSS status : is it on?, and is currently the phone position known? - so perhaps two statuses - ; maybe also geofence status) : to be discussed

For all buttons ; change color on click (from yellow to orange) quand on clique

** Parameter : Paramètres en FR
icon : parameter (gear)
-> all other buttons of the Profile screen

**Comment by DO3B** [comment]
I will start to work on this issue now. I found this cordova plugin which seems promising : https://www.npmjs.com/package/cordova.plugins.diagnostic#native-environment-required. I need to test it on both platforms before reaching any conclusion.

**Comment by PatGendre** [comment]
Ok, the plugin seems promising, it is mature and used (>40k donwloads for v4 on https://cordova.apache.org/plugins/?q=diagnostic , it look at the best choise in the list.
I understand that is not only a "readonly" lib, you could also change the status (but we don't need it, in principle)
Yes you have to test on both iOS and Android.

**Comment by DO3B** [comment]
To retrieve the network connection type on both iOS and Android, this plugin is needed https://www.npmjs.com/package/cordova-plugin-network-information (without the plugin, I can only retrieve the connection type of an Android phone).

**Comment by DO3B** [comment]
I just pushed a first version of the new Profile screen (https://github.com/fabmob/e-mission-phone-fabmob/commit/3621cb91bf0addbeb4b40c905bc96e4c7e23bb96). 

|Waiting for trip start|Ongoing trip|
|---|---|
|![Screenshot_1562672671](https://user-images.githubusercontent.com/17317703/60885553-21d1ed00-a250-11e9-8a45-689d4b14c8c8.png)|![Screenshot_1562672627](https://user-images.githubusercontent.com/17317703/60885558-272f3780-a250-11e9-85c7-e7f23b7de944.png)|

**Comment by PatGendre** [comment]
looks good :-)
So we are near to deploy an update?
Maybe we can wait for correction of current bugs (I did not succeed to run your pipeline...) , include the CO2 update, and for the position info we can wait until a later version?

**Comment by PatGendre** [comment]
maybe "Status"  / "Etat" instead for "Information" ?

**Comment by DO3B** [comment]
I will also change "Parameters" for "Settings" in English and "Paramètres" in French.

**Comment by PatGendre** [comment]
ok

**Comment by DO3B** [comment]
I added the current location of the user based on the location retrieve by the cordova plugin geolocation (https://github.com/fabmob/e-mission-phone-fabmob/commit/837c1a3dcad729a3fe28907d25452a82b8eb267e). 

|Location enabled|Location disabled|
|---|---|
|![Screenshot_1562750910](https://user-images.githubusercontent.com/17317703/60959431-75a00d00-a308-11e9-8728-6b659def885a.png)|![Screenshot_1562751991](https://user-images.githubusercontent.com/17317703/60959434-78026700-a308-11e9-8211-cae28907e0a4.png)|

**Comment by PatGendre** [comment]
excellent!
So for you the job is done now, can we consider the app ready for update?
Do we need to wait for some corrections by Shankari?

A question on the screenshot at right : the status is "start" so if we click on Start we will restart a new trip? When waiting for trip start ok to propose to start the trip, but do we need to propose to start the trip when the status is START?
Or what does START mean, maybe that the app is being started (not a trip)?
Would you think it useful to display also the last [transition](https://github.com/e-mission/e-mission-server/blob/master/emission/core/wrapper/transition.py) ?

I propose to come tomorrow morning at Icia so that we can test Shankari's patches and create new surveys.

**Comment by DO3B** [comment]
The "Start" state seems to be an initializing state. I am currently looking into the Data Collection plugin to better understand it. It appears when I am cutting the Location, I will change the button "Start trip" by "Initialize".

**Comment by PatGendre** [comment]
Ok, maybe it is too complicated for the user to add another action like Initialize? 

There are 4 states :  START = 0,     WAITING_FOR_TRIP_START = 1,     ONGOING_TRIP = 2, 
    TRACKING_STOPPED = 3, UNKNOWN = 3
You could also leave the button blank (no action) when the status is START or UNKNOWN and TRACKING_STOPPED and 
- display the End Trip button when status is ONGOING_TRIP
- display the Start Trip button when status is WAITING_FOR-START (which means I suppose that the user doesn't move and is in a geofence).

**Comment by DO3B** [comment]
Ok,  I will just "disabled" the button when the state is START, UNKNOWN or TRACKING_STOPPED.

**Comment by PatGendre** [comment]
Ok, good, I will update then the user Gdoc even if nobody reads it ;-)

**Comment by DO3B** [comment]
As you ask, "Dev zone" is now an `item-divider` instead of just a normal item in the `Parameters` list (https://github.com/fabmob/e-mission-phone-fabmob/commit/1481a1c991e422107f74342bfb6a5f53e182e07e). 


| Not expanded | Expanded|
|---|---|
|![Screenshot_1562856488](https://user-images.githubusercontent.com/17317703/61061136-fdb30f00-a3fb-11e9-9d34-a4f9627baa7b.png)|![Screenshot_1562856492](https://user-images.githubusercontent.com/17317703/61061179-0f94b200-a3fc-11e9-8cd1-96b84c5a0c40.png)|

**Comment by PatGendre** [comment]
molto bene, grazie :-)

**Comment by PatGendre** [comment]
@DO3B we also said that at the app launching, the Profile would be displayed instead of Dashboard. Is it easy to implement?

**Comment by DO3B** [comment]
It should be easy but the `Dashboard` seems more "user-friendly" than the `Profile`.

**Comment by PatGendre** [comment]
The problem I see with the dashboard is that it makes a quite long server request every time, and that the requests fails sometimes (if there is network connection, or sometimes because of bugs).
For this test, I think more useful to show the status so that the user knows how he is tracked (anyway the current users are not real users interested by their trips).
If it is very easy, I would like that we test it. We can revert it in a later version.

**Comment by DO3B** [comment]
Ok, It's done then (https://github.com/fabmob/e-mission-phone-fabmob/commit/8f227dfefae9144af22e5bceb12a9b283fe5a674). I left a comment explaining what to do just in case.
