### ISSUE TITLE
repair the "check sensed data" button in Profile screen

### ISSUE THREAD

**Issue by PatGendre** [fabmob/e-mission-phone-fabmob#9]
Currently this button does nothing
Check in other branches if somewhere we can find a working button...
See if it is easy to implement ourselves (should work similarly as email logs but filter only the data sent, only transitions, locations, or motion types.
If not, file an issue on e-mission-phone

**Comment by PatGendre** [comment]
@DO3B we have forgotten to ask Shankari yesterday, what was this "check sensed data" button for? Is it obsolete? Why is it difficult to see the sensed data displayed in the Recent screen?
In the short term we can **remove the button** from the profile because it doesn't work (Done)

In the mid term, it could be useful to display only the transitions/status/locations data as we understand this button was doing, but this could also be a server-side feature implemented for instance a new log file type with the sensed data logs (one file per dayf) for each user.

**Comment by DO3B** [comment]
I fixed the "Check sensed data" button (https://github.com/fabmob/e-mission-phone-fabmob/commit/83d5712ed42d11496f2850a71bc008dc206b8c24). It was juste a "true" to add to activate the metadata. 

|Locations|Motion Types|Transitions|
|---|---|---|
|![Screenshot_1564650499](https://user-images.githubusercontent.com/17317703/62281154-8cd8a300-b44d-11e9-85b0-4fe1bcb181bb.png)|![Screenshot_1564650505](https://user-images.githubusercontent.com/17317703/62281193-9cf08280-b44d-11e9-9afc-384f5ba78814.png)|![Screenshot_1564650509](https://user-images.githubusercontent.com/17317703/62281217-a974db00-b44d-11e9-9210-c1df5bd143ee.png)|
